name: flutter_devtools
description: Flutter DevTools

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_modular: ^5.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
