name: flutter_devtools
description: Flutter DevTools

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  ### Google Dependencies ###

  ### Core ###
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  bloc: ^8.1.0
  hydrated_bloc: ^9.0.0
  flutter_bloc: ^8.1.1

  ### Network ###

  ### Design ###
  # Icons
  ionicons: ^0.2.1

  ### Utils ###
  collection: ^1.16.0
  path_provider: ^2.0.11
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  storybook_flutter: ^0.11.3


  flutter:
    sdk: flutter
  # Web
  flutter_web_plugins:
    sdk: flutter
  # Translation
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  bloc_test: ^9.1.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  dart_code_metrics: ^4.19.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
