name: CI

on: 
  pull_request:
    branches: 
      - develop
      - release
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Generate
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Flutter Generate Translation
        run: flutter gen-l10n

      - name: Flutter Lint
        run: flutter analyze --fatal-warnings

      - name: Flutter Test
        run: flutter test --coverage --coverage-path ../coverage/lcov.info