name: CI

on: 
  pull_request:
    branches: 
      - develop
      - release
  workflow_dispatch:

jobs:
  flutter_devtools:
    name: Flutter DevTools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.5'
    - name: Flutter Pub Get
      run: flutter pub get
      
    - name: Flutter Generate Translation
      run: flutter gen-l10n
      
    - name: Flutter Lint
      run: flutter analyze --fatal-warning
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info
