name: Deploy Storybook

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Generate
        run: flutter pub run build_runner build --delete-conflicting-outputs

      #- name: Flutter Generate Translation
      #  run: flutter gen-l10n

      - name: Deploy Storybook
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: gh-pages
          webRenderer: html
          baseHref: /flutter_devtools/
